// Generated by npm run sync:admin — do not edit by hand.
window.__JJ_ADMIN__ = {
  "email": "contact@jamiljamila.com",
  "uid": "CXikFopbqfdKUy98g6gj9H6j2412",
  "page": "jamiljamila-admin.html",
  "pages": [
    "admin.html",
    "jamiljamila-admin.html"
  ]
};
