// Generated by npm run sync:admin — do not edit by hand.
window.__JJ_FIREBASE__ = {
  "apiKey": "AIzaSyDhVpX26TuxY3esDleW_pSug7etBfxzE08",
  "authDomain": "jamil-jamila.firebaseapp.com",
  "projectId": "jamil-jamila",
  "storageBucket": "jamil-jamila.firebasestorage.app",
  "messagingSenderId": "1094205754992",
  "appId": "1:1094205754992:web:fc31782da47f2b762e2eb5",
  "measurementId": "G-JF5C4BXD00"
};
window.__JJ_PRODUCTION_HOSTS__ = [
  "jamiljamila.com",
  "www.jamiljamila.com"
];
